// HVAT Service Worker for PWA offline support
// Cache version is determined by the app version (from Cargo.toml) and build hash.
// This ensures cache invalidation whenever the WASM is rebuilt.

// Version and build hash are passed via query string from index.html
// Format: sw.js?v=0.1.0&h=80a878fcf5e11dd7
// - Version comes from Cargo.toml (generated by build.rs into generated-version.js)
// - Hash comes from trunk's generated filename (e.g., hvat-80a878fcf5e11dd7.js)
const params = new URLSearchParams(self.location.search);
const APP_VERSION = params.get('v') || '0.0.0';
const BUILD_HASH = params.get('h') || Date.now().toString(36);
const CACHE_NAME = `hvat-cache-v${APP_VERSION}_${BUILD_HASH}`;

// Assets to cache immediately on install
// Note: The actual WASM and JS files have hashed names from Trunk build
// We'll cache them dynamically on first fetch
const PRECACHE_ASSETS = [
  '/',
  '/index.html',
  '/manifest.json',
  '/icons/icon-192x192.png',
  '/icons/icon-512x512.png'
];

// Install event - precache essential assets
self.addEventListener('install', (event) => {
  console.log(`[SW] Installing service worker... Cache: ${CACHE_NAME}`);

  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => {
        console.log('[SW] Precaching app shell');
        return cache.addAll(PRECACHE_ASSETS);
      })
      .then(() => {
        // Skip waiting to activate immediately
        return self.skipWaiting();
      })
      .catch((error) => {
        console.error('[SW] Precache failed:', error);
      })
  );
});

// Activate event - clean up old caches
self.addEventListener('activate', (event) => {
  console.log(`[SW] Activating service worker... Cache: ${CACHE_NAME}`);

  event.waitUntil(
    caches.keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames
            .filter((name) => name.startsWith('hvat-cache-') && name !== CACHE_NAME)
            .map((name) => {
              console.log('[SW] Deleting old cache:', name);
              return caches.delete(name);
            })
        );
      })
      .then(() => {
        // Take control of all pages immediately
        return self.clients.claim();
      })
  );
});

// Fetch event - serve from cache, fall back to network
self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);

  // Only handle same-origin requests
  if (url.origin !== location.origin) {
    return;
  }

  // For worker scripts, we still want to cache them for offline support
  // but we need to be careful not to interfere with their message passing.
  // The worker WASM and JS files should be cached like other assets.
  // Note: request.destination === 'worker' is for the initial worker script load,
  // which we DO want to cache. Requests made BY the worker have different destinations.

  // For navigation requests (HTML), use network-first strategy.
  // IMPORTANT: Use cache: 'no-store' to bypass browser HTTP cache and always
  // get fresh HTML from server. This ensures we get the latest SRI hashes.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request, { cache: 'no-store' })
        .then((response) => {
          // Cache the latest version for offline use
          if (response.ok) {
            const responseClone = response.clone();
            caches.open(CACHE_NAME).then((cache) => {
              cache.put(request, responseClone);
            });
          }
          return response;
        })
        .catch(() => {
          // Offline - serve from cache
          return caches.match(request)
            .then((response) => response || caches.match('/index.html'));
        })
    );
    return;
  }

  // For WASM and JS files with content hashes in filenames:
  // Use cache-first strategy. Files have unique hashes (e.g., hvat-7283580183dda6a8.js),
  // so a cache hit means we have the exact file we need - saves bandwidth.
  // A cache miss means it's a new version, so we fetch from network.
  //
  // NOTE: SRI is disabled in Trunk.toml (no_sri = true) to allow offline caching.
  if (url.pathname.endsWith('.wasm') || url.pathname.endsWith('.js')) {
    event.respondWith(
      caches.match(request)
        .then((cachedResponse) => {
          if (cachedResponse) {
            console.log('[SW] Cache hit:', url.pathname);
            return cachedResponse;
          }

          // Cache miss - fetch from network
          console.log('[SW] Cache miss, fetching:', url.pathname);
          return fetch(request)
            .then((response) => {
              if (response.ok) {
                const responseClone = response.clone();
                caches.open(CACHE_NAME).then((cache) => {
                  console.log('[SW] Caching:', url.pathname);
                  cache.put(request, responseClone);
                });
              }
              return response;
            })
            .catch((error) => {
              console.error('[SW] Fetch failed:', url.pathname, error);
              return new Response(
                `Resource not available offline: ${url.pathname}\n\nPlease load the app while online first to cache all assets.`,
                {
                  status: 503,
                  statusText: 'Service Unavailable',
                  headers: { 'Content-Type': 'text/plain' }
                }
              );
            });
        })
    );
    return;
  }

  // For other assets (icons, fonts, etc.), use stale-while-revalidate
  event.respondWith(
    caches.match(request)
      .then((cachedResponse) => {
        const fetchPromise = fetch(request)
          .then((networkResponse) => {
            if (networkResponse.ok) {
              const responseClone = networkResponse.clone();
              caches.open(CACHE_NAME).then((cache) => {
                cache.put(request, responseClone);
              });
            }
            return networkResponse;
          })
          .catch(() => cachedResponse);

        return cachedResponse || fetchPromise;
      })
  );
});

// Handle messages from the main app
self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') {
    self.skipWaiting();
  }

  if (event.data === 'getVersion') {
    event.ports[0].postMessage({ version: APP_VERSION, hash: BUILD_HASH, cache: CACHE_NAME });
  }
});
